### ISSUE TITLE
Implement gRPC service

### ISSUE THREAD

**Issue by oubiwann** [hexagram30/noise#4]
Preparation:
* [ ] Add ASCII support (see #6)
* [ ] Update current CLI usage (see #5)
* [ ] Define service features (see #7)
Dev tasks:
* [ ] Create protobuf protocols that match features defined in #7
* [ ] Restructure app to follow the example given in #2:
   * [ ] Update `Cargo.toml` for gRPC
   * [ ] Add builder
   * [ ] Add server impl

**Comment by oubiwann** [comment]
See this comment for an example:
* https://github.com/hexagram30/noise/issues/2#issuecomment-572114807
